spring.application.name=gms-backend-spring

# Env
spring.config.import=optional:file:./.env[.properties],optional:file:../.env[.properties]

# Flyway
spring.flyway.locations=classpath:db/migration/mysql
spring.flyway.group=true

# Mysql Database
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

# Session
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=6h

# JWT
jwt.secret=${JWT_SECRET}

# Quartz
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.threadPool.threadCount=4
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.overwrite-existing-jobs=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.writer-with-order-by-keys=true
springdoc.swagger-ui.defaultModelsExpandDepth=1

# minIo
minio.url=http://localhost:9000
minio.accessKey=admin
minio.secretKey=password123
minio.bucket.public=gms-public
minio.bucket.private=gms-private

# JPA
spring.jpa.open-in-view=false

# Logs
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF

# Debug
#spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Ensure that logging output is visible in the console
#logging.level.org.springframework.boot=DEBUG

# Logs the actual SQL statements (SELECT, UPDATE, etc.)
#logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# Logs the parameters being passed (the Session ID, attributes, etc.)
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE